service: sls-ocr

provider:
  name: aws
  runtime: nodejs20.x

functions:
  ocr:
    handler: src/index.ocr
    timeout: 900
    url: true

package:
  include:
    - node_modules/tesseract.js/**
    - node_modules/bmp-js/**
    - node_modules/idb-keyval/**
    - node_modules/is-electron/**
    - node_modules/is-url/**
    - node_modules/node-fetch/**
    - node_modules/regenerator-runtime/**
    - node_modules/tesseract.js-core/**
    - node_modules/wasm-feature-detect/**
    - node_modules/zlibjs/**
    - node_modules/whatwg-url/**
    - node_modules/tr46/**
    - node_modules/webidl-conversions/**

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - '@divine-bridge/serverless-offline-lambda-function-urls'
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
    format: cjs
    outputFileExtension: .cjs
  serverless-offline:
    lambdaPort: 3010
    urlLambdaFunctionsHttpPort: 5010
    urlLambdaFunctionsHttpVerbs:
      - POST
