service: sls-ocr

provider:
  name: aws
  runtime: nodejs20.x

functions:
  ocr:
    handler: src/index.handler
    timeout: 900
    events:
      - httpApi: '*'

package:
  include:
    - node_modules/tesseract.js/**
    - node_modules/bmp-js/**
    - node_modules/idb-keyval/**
    - node_modules/is-electron/**
    - node_modules/is-url/**
    - node_modules/node-fetch/**
    - node_modules/regenerator-runtime/**
    - node_modules/tesseract.js-core/**
    - node_modules/wasm-feature-detect/**
    - node_modules/zlibjs/**
    - node_modules/whatwg-url/**
    - node_modules/tr46/**
    - node_modules/webidl-conversions/**

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
    lambdaPort: 3010
    httpPort: 5010
  esbuild:
    bundle: true
    minify: false
    format: cjs
    outputFileExtension: .cjs
