service: sls-backup

provider:
  name: aws
  runtime: nodejs22.x

functions:
  backup:
    handler: src/index.backup
    timeout: 900
    url: true

package:
  patterns:
    - mongodump

build:
  esbuild:
    configFile: esbuild.config.js

plugins:
  - serverless-dotenv-plugin
  - '@divine-bridge/serverless-offline-lambda-function-urls'
  - serverless-offline

custom:
  serverless-offline:
    lambdaPort: 3012
    urlLambdaFunctionsHttpPort: 5012
    urlLambdaFunctionsHttpVerbs:
      - POST
