import { DiscordBotAPI } from '@divine-bridge/common';
import { PermissionsString } from 'discord.js';

import { Env } from './env.js';

export const discordBotApi = new DiscordBotAPI(Env.DISCORD_BOT_TOKEN);

export const readablePermissionsMap: Record<PermissionsString, string> = {
  AddReactions: 'Add Reactions',
  Administrator: 'Administrator',
  AttachFiles: 'Attach Files',
  BanMembers: 'Ban Members',
  ChangeNickname: 'Change Nickname',
  Connect: 'Connect',
  CreateInstantInvite: 'Create Instant Invite',
  CreatePrivateThreads: 'Create Private Threads',
  CreatePublicThreads: 'Create Public Threads',
  DeafenMembers: 'Deafen Members',
  EmbedLinks: 'Embed Links',
  KickMembers: 'Kick Members',
  ManageChannels: 'Manage Channels',
  ManageEmojisAndStickers: 'Manage Emojis and Stickers',
  ManageEvents: 'Manage Events',
  ManageGuild: 'Manage Guild',
  ManageGuildExpressions: 'Manage Guild Expressions',
  ManageMessages: 'Manage Messages',
  ManageNicknames: 'Manage Nicknames',
  ManageRoles: 'Manage Roles',
  ManageThreads: 'Manage Threads',
  ManageWebhooks: 'Manage Webhooks',
  MentionEveryone: 'Mention Everyone',
  ModerateMembers: 'Moderate Members',
  MoveMembers: 'Move Members',
  MuteMembers: 'Mute Members',
  PrioritySpeaker: 'Priority Speaker',
  ReadMessageHistory: 'Read Message History',
  RequestToSpeak: 'Request To Speak',
  SendMessages: 'Send Messages',
  SendMessagesInThreads: 'Send Messages in Threads',
  SendTTSMessages: 'Send TTS Messages',
  SendVoiceMessages: 'Send Voice Messages',
  Stream: 'Stream',
  Speak: 'Speak',
  UseApplicationCommands: 'Use Application Commands',
  UseEmbeddedActivities: 'Use Embedded Activities',
  UseExternalEmojis: 'Use External Emojis',
  UseExternalSounds: 'Use External Sounds',
  UseExternalStickers: 'Use External Stickers',
  UseSoundboard: 'Use Soundboard',
  UseVAD: 'Use VAD',
  ViewAuditLog: 'View Audit Log',
  ViewChannel: 'View Channel',
  ViewCreatorMonetizationAnalytics: 'View Creator Monetization Analytics',
  ViewGuildInsights: 'View Guild Insights',
};
