service: sls-bot

provider:
  name: aws
  runtime: nodejs20.x

functions:
  bot:
    handler: src/index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 3000
  esbuild:
    bundle: true
    minify: false
    format: cjs
    outputFileExtension: .cjs
