service: sls-check-membership

provider:
  name: aws
  runtime: nodejs20.x

functions:
  check-auth-membership:
    handler: src/index.checkAuthMembership
    timeout: 900
    url: true
  check-screenshot-membership:
    handler: src/index.checkScreenshotMembership
    timeout: 900
    url: true

package:
  include:
    - node_modules/pino-abstract-transport/**
    - node_modules/split2/**
    - node_modules/readable-stream/**
    - node_modules/process/**

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - '@divine-bridge/serverless-offline-lambda-function-urls'
  - serverless-offline

custom:
  esbuild:
    config: esbuild.config.cjs
  serverless-offline:
    lambdaPort: 3011
    urlLambdaFunctionsHttpPort: 5011
    urlLambdaFunctionsHttpVerbs:
      - POST
