name: Deploy sls-check-membership to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      deploy: ${{ steps.filter.outputs.deploy }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Filter path
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            deploy:
              - 'apps/sls-check-membership/**'

  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.deploy == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/sls-check-membership
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Load environment variables
        run: echo "${{ secrets.SLS_CHECK_MEMBERSHIP_ENV }}" | base64 --decode >> .env.production.local

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: npx serverless deploy --stage production
